In [66]:
import numpy as np



In [75]:

#M = np.array([[1, 2, 3],[4,5,6],[7,8,9]])
M = np.random.randint(1,10,size = (3,3)) #Random original matrix
print('M:\n', M )

n,_ = M.shape 

Inv = np.identity(n)

R = np.hstack((M,Inv))
print('\nR:\n',np.round(R, 2))

for j in range(n): #Loop for columns
    
    for k in range(j,2*n): #Making diagonal element 1
        R[j,k] = R[j,k] / R[j,j]
    
    print('\nElement', j, j, 'Operation:\n', np.round(R,2))
    
    for i in range(n): #Loop for rows
       
        if i !=j: #Not diagonal rows (pivot rows)
            Multiplier = R[i,j]
            
            for k in range(j,2*n):
                R[i,k] = R[i,k]- Multiplier*R[j,k]

            print('\nRow operation', i, '\n', np.round(R,2))
            
np.set_printoptions(suppress=True) #Avoid Scientific notation

print('Inverse Matrix:\n', np.round(R[...,n::]))

M:
 [[3 1 1]
 [5 7 4]
 [2 9 6]]

R:
 [[3. 1. 1. 1. 0. 0.]
 [5. 7. 4. 0. 1. 0.]
 [2. 9. 6. 0. 0. 1.]]

Element 0 0 Operation:
 [[1. 1. 1. 1. 0. 0.]
 [5. 7. 4. 0. 1. 0.]
 [2. 9. 6. 0. 0. 1.]]

Row operation 1 
 [[ 1.  1.  1.  1.  0.  0.]
 [ 0.  2. -1. -5.  1.  0.]
 [ 2.  9.  6.  0.  0.  1.]]

Row operation 2 
 [[ 1.  1.  1.  1.  0.  0.]
 [ 0.  2. -1. -5.  1.  0.]
 [ 0.  7.  4. -2.  0.  1.]]

Element 1 1 Operation:
 [[ 1.  1.  1.  1.  0.  0.]
 [ 0.  1. -1. -5.  1.  0.]
 [ 0.  7.  4. -2.  0.  1.]]

Row operation 0 
 [[ 1.  0.  2.  6. -1.  0.]
 [ 0.  1. -1. -5.  1.  0.]
 [ 0.  7.  4. -2.  0.  1.]]

Row operation 2 
 [[ 1.  0.  2.  6. -1.  0.]
 [ 0.  1. -1. -5.  1.  0.]
 [ 0.  0. 11. 33. -7.  1.]]

Element 2 2 Operation:
 [[ 1.  0.  2.  6. -1.  0.]
 [ 0.  1. -1. -5.  1.  0.]
 [ 0.  0.  1. 33. -7.  1.]]

Row operation 0 
 [[  1.   0.   0. -60.  13.  -2.]
 [  0.   1.  -1.  -5.   1.   0.]
 [  0.   0.   1.  33.  -7.   1.]]

Row operation 1 
 [[  1.   0.   0. -60.  13.  -2.]
 [  0.   1.   0.  28.